[package]
name = "dorian"
version = "0.2.0"
edition = "2018"
description = "The intuitive LLVM abstraction written in Rust."
license-file = "LICENSE"
homepage = "https://github.com/peterhenryd/dorian"

[dependencies]
llvm-sys = "140.0.2"