[package]
name = "dorian"
version = "0.1.0"
edition = "2018"
description = "The intuitive LLVM abstraction written in Rust."
license-file = "LICENSE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
llvm-sys = "120.1.0"